version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ../backend:/app
      - ../backend/node_modules:/app/node_modules
    depends_on:
      - supabase
    networks:
      - app-network

  frontend:
    build:
      context: ../src
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ../src:/app
      - ../src/node_modules:/app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://backend:5000
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    networks:
      - app-network

  supabase:
    image: supabase/supabase
    ports:
      - "54321:54321"
      - "54322:54322"
      - "54323:54323"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
